/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as LabRouteImport } from './routes/lab'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TracerRouteImport } from './routes/tracer'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TracerRoute = TracerRouteImport.update({
  id: '/tracer',
  path: '/tracer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/explain': typeof ExplainRoute
  '/lab': typeof LabRoute
  '/network': typeof NetworkRoute
  '/timeline': typeof TimelineRoute
  '/tracer': typeof TracerRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/explain': typeof ExplainRoute
  '/lab': typeof LabRoute
  '/network': typeof NetworkRoute
  '/timeline': typeof TimelineRoute
  '/tracer': typeof TracerRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/explain': typeof ExplainRoute
  '/lab': typeof LabRoute
  '/network': typeof NetworkRoute
  '/timeline': typeof TimelineRoute
  '/tracer': typeof TracerRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/explain'
    | '/lab'
    | '/network'
    | '/timeline'
    | '/tracer'
    | '/accounts/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/explain'
    | '/lab'
    | '/network'
    | '/timeline'
    | '/tracer'
    | '/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/explain'
    | '/lab'
    | '/network'
    | '/timeline'
    | '/tracer'
    | '/accounts/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ExplainRoute: typeof ExplainRoute
  LabRoute: typeof LabRoute
  NetworkRoute: typeof NetworkRoute
  TimelineRoute: typeof TimelineRoute
  TracerRoute: typeof TracerRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracer': {
      id: '/tracer'
      path: '/tracer'
      fullPath: '/tracer'
      preLoaderRoute: typeof TracerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ExplainRoute: ExplainRoute,
  LabRoute: LabRoute,
  NetworkRoute: NetworkRoute,
  TimelineRoute: TimelineRoute,
  TracerRoute: TracerRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
